---
title: 'Ausnahmen: Die failwith-Funktion'
description: Erfahren Sie, wie die Funktion "Failwith" F#-Ausnahme generiert.
ms.date: 05/16/2016
ms.openlocfilehash: 08107966ddc2f55625347deb92d224b286df7761
ms.sourcegitcommit: 8699383914c24a0df033393f55db3369db728a7b
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 05/15/2019
ms.locfileid: "65641947"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="4853b-103">Ausnahmen: Die failwith-Funktion</span><span class="sxs-lookup"><span data-stu-id="4853b-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="4853b-104">Die `failwith` -Funktion generiert eine F# Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="4853b-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="4853b-105">Syntax</span><span class="sxs-lookup"><span data-stu-id="4853b-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="4853b-106">Hinweise</span><span class="sxs-lookup"><span data-stu-id="4853b-106">Remarks</span></span>

<span data-ttu-id="4853b-107">Die *Fehlermeldungszeichenfolge* in der vorherigen Syntax ist ein Zeichenfolgenliteral oder ein Wert vom Typ `string`.</span><span class="sxs-lookup"><span data-stu-id="4853b-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="4853b-108">Es wird die `Message` -Eigenschaft der Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="4853b-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="4853b-109">Die Ausnahme, die vom generierten `failwith` ist eine `System.Exception` Ausnahme aus, die ein Verweis ist mit dem Namen `Failure` in F# Code.</span><span class="sxs-lookup"><span data-stu-id="4853b-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="4853b-110">Der folgende Code veranschaulicht die Verwendung von `failwith` eine Ausnahme ausgel√∂st.</span><span class="sxs-lookup"><span data-stu-id="4853b-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="4853b-111">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="4853b-111">See also</span></span>

- [<span data-ttu-id="4853b-112">Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="4853b-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="4853b-113">Ausnahmetypen</span><span class="sxs-lookup"><span data-stu-id="4853b-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="4853b-114">Ausnahmen: Die `try...with` Ausdruck</span><span class="sxs-lookup"><span data-stu-id="4853b-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="4853b-115">Ausnahmen: Die `try...finally` Ausdruck</span><span class="sxs-lookup"><span data-stu-id="4853b-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="4853b-116">Ausnahmen: Die `raise`-Funktion</span><span class="sxs-lookup"><span data-stu-id="4853b-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
