---
title: 'Ausnahmen: Die failwith-Funktion'
description: Erfahren Sie, wie die Funktion "Failwith" F#-Ausnahme generiert.
ms.date: 05/16/2016
ms.openlocfilehash: f2c86362d5bdde7bab55751f019965a5f4ca6236
ms.sourcegitcommit: f20dd18dbcf2275513281f5d9ad7ece6a62644b4
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 07/30/2019
ms.locfileid: "68630328"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="39382-103">Ausnahmen: Die failwith-Funktion</span><span class="sxs-lookup"><span data-stu-id="39382-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="39382-104">Die `failwith` Funktion generiert eine F# Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="39382-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="39382-105">Syntax</span><span class="sxs-lookup"><span data-stu-id="39382-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="39382-106">Hinweise</span><span class="sxs-lookup"><span data-stu-id="39382-106">Remarks</span></span>

<span data-ttu-id="39382-107">Der *Fehler-Message-String* in der vorherigen Syntax ist eine Literalzeichenfolge oder ein `string`Wert des Typs.</span><span class="sxs-lookup"><span data-stu-id="39382-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="39382-108">Sie wird `Message` zur-Eigenschaft der Ausnahme.</span><span class="sxs-lookup"><span data-stu-id="39382-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="39382-109">Eine Ausnahme `failwith` , die von generiert wird, ist eine `System.Exception` -Ausnahme, bei der es sich um einen F# Verweis mit dem Namen `Failure` im Code handelt.</span><span class="sxs-lookup"><span data-stu-id="39382-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="39382-110">Der folgende Code veranschaulicht die Verwendung von `failwith` , um eine Ausnahme auszul√∂sen.</span><span class="sxs-lookup"><span data-stu-id="39382-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](~/samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="39382-111">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="39382-111">See also</span></span>

- [<span data-ttu-id="39382-112">Ausnahmebehandlung</span><span class="sxs-lookup"><span data-stu-id="39382-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="39382-113">Ausnahmetypen</span><span class="sxs-lookup"><span data-stu-id="39382-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="39382-114">Ausnahmen: Der `try...with` Ausdruck</span><span class="sxs-lookup"><span data-stu-id="39382-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="39382-115">Ausnahmen: Der `try...finally` Ausdruck</span><span class="sxs-lookup"><span data-stu-id="39382-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="39382-116">Ausnahmen: Die `raise`-Funktion</span><span class="sxs-lookup"><span data-stu-id="39382-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)
